name: Go Unit Tests

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21' # Specify your Go version here

    - name: Cache Go modules
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-

    - name: Install dependencies
      run: go mod tidy

    - name: Check for git diff after go mod tidy
      run: |
        git diff --exit-code --color
      if: ${{ always() }}
      continue-on-error: true

    - name: Fail if there are uncommitted changes
      run: |
        echo "Uncommitted changes found after 'go mod tidy'. Please commit changes."
        exit 1
      if: ${{ failure() }}

    - name: Build the project
      run: go build ./...

    - name: Run tests
      run: go test ./...