name: test

permissions:
  contents: read

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:

env:
  FOUNDRY_PROFILE: ci

jobs:
  build:
    strategy:
      fail-fast: true
    name: Foundry build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@67d408dce6d39cfcfada695c6921c917218372cd # v1.9.1

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes

  test:
    strategy:
      fail-fast: true
    name: Foundry test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@67d408dce6d39cfcfada695c6921c917218372cd # v1.9.1

      - name: Run Forge tests
        run: |
          forge test --ffi -vvv
